/**
 * Shared types for the decisions index written by the daemon
 * and read by the MCP server.
 *
 * Index location: ~/.context-keeper/index.json
 */

export interface DecisionEntry {
  /** UUID generated by daemon at capture time */
  id: string;
  /** Absolute path to the project root */
  projectPath: string;
  /** Human-readable project name (basename of projectPath) */
  projectName: string;
  /** Basename of the source .jsonl file (without extension) */
  sessionId: string;
  /** Decision text, max 100 chars, past-tense action format */
  text: string;
  /** ISO 8601 timestamp */
  capturedAt: string;
}

export interface DecisionIndex {
  version: 1;
  decisions: DecisionEntry[];
}
