import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as crypto from 'crypto';

// ---------------------------------------------------------------------------
// Canonical types — must match packages/mcp/src/types.ts (DecisionEntry / DecisionIndex).
// If @tom's types diverge, align both sides before merging.
// ---------------------------------------------------------------------------

export interface DecisionEntry {
  /** Unique ID for the decision (cuid-style, generated by daemon). */
  id: string;
  /** Absolute path to the project directory. */
  projectPath: string;
  /** Human-readable project name (basename of projectPath). */
  projectName: string;
  /** Basename of the source .jsonl file (session identifier). */
  sessionId: string;
  /** The decision text, max ~100 chars. */
  text: string;
  /** ISO 8601 timestamp when the decision was captured. */
  capturedAt: string;
}

export interface DecisionIndex {
  /** Schema version — bump if shape changes to allow migrations. */
  version: 1;
  /** All captured decisions, sorted descending by capturedAt (newest first). */
  decisions: DecisionEntry[];
}

// ---------------------------------------------------------------------------

const INDEX_DIR = path.join(os.homedir(), '.context-keeper');
const INDEX_PATH = path.join(INDEX_DIR, 'index.json');
const SCHEMA_VERSION = 1;

function readIndex(): DecisionIndex {
  if (!fs.existsSync(INDEX_PATH)) {
    return { version: 1, decisions: [] };
  }
  try {
    const raw = fs.readFileSync(INDEX_PATH, 'utf-8');
    const parsed = JSON.parse(raw) as DecisionIndex;
    if (!parsed.version || !Array.isArray(parsed.decisions)) {
      return { version: 1, decisions: [] };
    }
    return parsed;
  } catch {
    return { version: 1, decisions: [] };
  }
}

function writeIndex(index: DecisionIndex): void {
  fs.mkdirSync(INDEX_DIR, { recursive: true });
  fs.writeFileSync(INDEX_PATH, JSON.stringify(index, null, 2) + '\n', 'utf-8');
}

/** Simple collision-resistant ID (no external deps). */
function generateId(): string {
  return crypto.randomBytes(12).toString('base64url');
}

/**
 * Appends new decisions to ~/.context-keeper/index.json.
 * Deduplicates by (projectPath, sessionId, text) to avoid re-adding on retry.
 * Entries are kept sorted newest-first.
 */
export function appendToIndex(
  projectPath: string,
  sessionId: string,
  decisions: string[],
): void {
  if (decisions.length === 0) return;

  const index = readIndex();
  const capturedAt = new Date().toISOString();
  const projectName = path.basename(projectPath);

  // Build a dedup key set for existing entries in this session
  const existingKeys = new Set(
    index.decisions
      .filter((e) => e.projectPath === projectPath && e.sessionId === sessionId)
      .map((e) => e.text),
  );

  const newEntries: DecisionEntry[] = decisions
    .filter((text) => !existingKeys.has(text))
    .map((text) => ({
      id: generateId(),
      projectPath,
      projectName,
      sessionId,
      text,
      capturedAt,
    }));

  if (newEntries.length === 0) return;

  index.decisions = [...newEntries, ...index.decisions];
  index.version = 1;
  writeIndex(index);
}

/** Returns the path to the index file (useful for tests/CLI). */
export function getIndexPath(): string {
  return INDEX_PATH;
}
